"""Completion recipe for curl."""

from __future__ import annotations

import shutil

from ..commands import flag_args, registry as command_registry
from ..completion import ChoiceCompleter, FileCompleter

CURL_OPTIONS: dict[str, str] = {
    "-A": "User-Agent string to send",
    "-b": "send cookies (string or load from file)",
    "-c": "write cookies to file after operation",
    "-d": "send data — POST body (or @file for file body)",
    "-D": "write response headers to file",
    "-e": "Referer URL to send",
    "-f": "fail silently on HTTP errors (no output on 4xx/5xx)",
    "-F": "multipart form upload (e.g. file=@/path)",
    "-G": "use GET — append -d data as query string",
    "-H": "add a header (repeatable, e.g. 'Authorization: ...')",
    "-i": "include response headers in output",
    "-I": "fetch headers only (HEAD)",
    "-J": "use Content-Disposition filename for -O",
    "-k": "allow insecure server connections (skip TLS verify)",
    "-K": "read curl options from a config file",
    "-L": "follow redirects",
    "-m": "maximum time allowed for the transfer (seconds)",
    "-N": "disable buffering of the output stream",
    "-o": "write output to FILE instead of stdout",
    "-O": "write output to a local file named like the remote one",
    "-r": "retrieve only bytes within RANGE",
    "-s": "silent — no progress meter or error messages",
    "-S": "show errors even with -s",
    "-T": "upload a file (PUT-style)",
    "-u": "user[:password] for server auth",
    "-v": "verbose",
    "-w": "what to display after a transfer",
    "-x": "use the given proxy",
    "-X": "specify HTTP method (GET, POST, PUT, DELETE, …)",
    "-Z": "perform requests in parallel",
    "--cacert": "CA certificate file to verify the peer",
    "--cert": "client certificate file (with optional password)",
    "--connect-timeout": "maximum time allowed for connection (seconds)",
    "--cookie": "send cookies (string or load from file)",
    "--cookie-jar": "write cookies to file after operation",
    "--data-binary": "POST body sent verbatim (no @file processing)",
    "--data-raw": "POST body verbatim (no @file processing, allow @ literal)",
    "--data-urlencode": "POST data, URL-encoded",
    "--digest": "use HTTP Digest authentication",
    "--fail": "fail silently on HTTP errors",
    "--form": "multipart form upload",
    "--head": "fetch headers only",
    "--header": "add a request header",
    "--http1.0": "use HTTP/1.0",
    "--http1.1": "use HTTP/1.1",
    "--http2": "use HTTP/2",
    "--http3": "use HTTP/3",
    "--include": "include response headers in output",
    "--insecure": "allow insecure server connections (skip TLS verify)",
    "--ipv4": "resolve names to IPv4 addresses",
    "--ipv6": "resolve names to IPv6 addresses",
    "--key": "private key file",
    "--limit-rate": "limit transfer speed (e.g. 1K, 1M)",
    "--location": "follow redirects",
    "--max-redirs": "maximum number of redirects to follow",
    "--max-time": "maximum time allowed for transfer (seconds)",
    "--no-progress-meter": "do not show progress meter",
    "--noproxy": "list of hosts that should not use the proxy",
    "--output": "write output to FILE",
    "--proxy": "use the given proxy",
    "--proxy-user": "proxy user[:password]",
    "--range": "retrieve only bytes within RANGE",
    "--referer": "Referer URL to send",
    "--request": "specify HTTP method",
    "--resolve": "force a host:port to resolve to an address",
    "--retry": "retry up to N times on transient failures",
    "--retry-delay": "wait given seconds between retries",
    "--retry-max-time": "give up retrying after given seconds",
    "--silent": "silent mode",
    "--show-error": "show errors even when silent",
    "--ssl-no-revoke": "do not check certificate revocation (Schannel)",
    "--tlsv1.2": "use TLS 1.2 or later",
    "--tlsv1.3": "use TLS 1.3 or later",
    "--upload-file": "upload a file (PUT-style)",
    "--url": "URL to work with",
    "--user": "user[:password] for server auth",
    "--user-agent": "User-Agent string to send",
    "--verbose": "verbose",
    "--write-out": "what to display after a transfer",
}

_HTTP_METHODS = [
    "GET", "POST", "PUT", "DELETE", "PATCH", "HEAD", "OPTIONS",
    "TRACE", "CONNECT",
]

CURL_ARGS: dict[str, object] = {
    "-A": "USER-AGENT",
    "--user-agent": "USER-AGENT",
    "-b": "DATA|FILE",
    "--cookie": "DATA|FILE",
    "-c": ("FILE", FileCompleter()),
    "--cookie-jar": ("FILE", FileCompleter()),
    "-d": "DATA",
    "--data-binary": "DATA|@FILE",
    "--data-raw": "DATA",
    "--data-urlencode": "DATA",
    "-D": ("FILE", FileCompleter()),
    "-e": "URL",
    "--referer": "URL",
    "-F": "NAME=CONTENT",
    "--form": "NAME=CONTENT",
    "-H": "HEADER",
    "--header": "HEADER",
    "-K": ("FILE", FileCompleter()),
    "-m": "SECONDS",
    "--max-time": "SECONDS",
    "--connect-timeout": "SECONDS",
    "--retry": "N",
    "--retry-delay": "SECONDS",
    "--retry-max-time": "SECONDS",
    "--max-redirs": "N",
    "-o": ("FILE", FileCompleter()),
    "--output": ("FILE", FileCompleter()),
    "-r": "RANGE",
    "--range": "RANGE",
    "-T": ("FILE", FileCompleter()),
    "--upload-file": ("FILE", FileCompleter()),
    "-u": "USER[:PASSWORD]",
    "--user": "USER[:PASSWORD]",
    "--proxy-user": "USER[:PASSWORD]",
    "-w": "FORMAT",
    "--write-out": "FORMAT",
    "-x": "[PROTOCOL://]HOST[:PORT]",
    "--proxy": "[PROTOCOL://]HOST[:PORT]",
    "--noproxy": "HOST-LIST",
    "-X": ("METHOD", ChoiceCompleter(_HTTP_METHODS)),
    "--request": ("METHOD", ChoiceCompleter(_HTTP_METHODS)),
    "--cacert": ("FILE", FileCompleter()),
    "--cert": ("FILE", FileCompleter()),
    "--key": ("FILE", FileCompleter()),
    "--limit-rate": "SPEED",
    "--resolve": "HOST:PORT:ADDR",
    "--url": "URL",
}


def register() -> None:
    if shutil.which("curl") is None:
        return
    command_registry.command(
        "curl",
        help="transfer data from or to a URL",
        params=flag_args(CURL_OPTIONS, values=CURL_ARGS),
    )
