"""Completion recipe for curl."""

from __future__ import annotations

import shutil

from ..commands import arg, registry as command_registry
from ..completion import ChoiceCompleter, FileCompleter

_HTTP_METHODS = [
    "GET", "POST", "PUT", "DELETE", "PATCH", "HEAD", "OPTIONS",
    "TRACE", "CONNECT",
]


def register() -> None:
    if shutil.which("curl") is None:
        return
    command_registry.command(
        "curl",
        help="transfer data from or to a URL",
        params=[
            arg("-A", metavar="USER-AGENT", help="User-Agent string to send"),
            arg("-b", metavar="DATA|FILE", help="send cookies (string or load from file)"),
            arg("-c", metavar="FILE", help="write cookies to file after operation",
                completer=FileCompleter()),
            arg("-d", metavar="DATA", help="send data — POST body (or @file for file body)"),
            arg("-D", metavar="FILE", help="write response headers to file", completer=FileCompleter()),
            arg("-e", metavar="URL", help="Referer URL to send"),
            arg("-f", action="store_true", help="fail silently on HTTP errors (no output on 4xx/5xx)"),
            arg("-F", metavar="NAME=CONTENT", help="multipart form upload (e.g. file=@/path)"),
            arg("-G", action="store_true", help="use GET — append -d data as query string"),
            arg("-H", metavar="HEADER", help="add a header (repeatable, e.g. 'Authorization: ...')"),
            arg("-i", action="store_true", help="include response headers in output"),
            arg("-I", action="store_true", help="fetch headers only (HEAD)"),
            arg("-J", action="store_true", help="use Content-Disposition filename for -O"),
            arg("-k", action="store_true", help="allow insecure server connections (skip TLS verify)"),
            arg("-K", metavar="FILE", help="read curl options from a config file", completer=FileCompleter()),
            arg("-L", action="store_true", help="follow redirects"),
            arg("-m", metavar="SECONDS", help="maximum time allowed for the transfer (seconds)"),
            arg("-N", action="store_true", help="disable buffering of the output stream"),
            arg("-o", metavar="FILE", help="write output to FILE instead of stdout", completer=FileCompleter()),
            arg("-O", action="store_true", help="write output to a local file named like the remote one"),
            arg("-r", metavar="RANGE", help="retrieve only bytes within RANGE"),
            arg("-s", action="store_true", help="silent — no progress meter or error messages"),
            arg("-S", action="store_true", help="show errors even with -s"),
            arg("-T", metavar="FILE", help="upload a file (PUT-style)", completer=FileCompleter()),
            arg("-u", metavar="USER[:PASSWORD]", help="user[:password] for server auth"),
            arg("-v", action="store_true", help="verbose"),
            arg("-w", metavar="FORMAT", help="what to display after a transfer"),
            arg("-x", metavar="[PROTOCOL://]HOST[:PORT]", help="use the given proxy"),
            arg("-X", metavar="METHOD", help="specify HTTP method (GET, POST, PUT, DELETE, …)",
                completer=ChoiceCompleter(_HTTP_METHODS)),
            arg("-Z", action="store_true", help="perform requests in parallel"),
            arg("--cacert", metavar="FILE", help="CA certificate file to verify the peer", completer=FileCompleter()),
            arg("--cert", metavar="FILE", help="client certificate file (with optional password)",
                completer=FileCompleter()),
            arg("--connect-timeout", metavar="SECONDS", help="maximum time allowed for connection (seconds)"),
            arg("--cookie", metavar="DATA|FILE", help="send cookies (string or load from file)"),
            arg("--cookie-jar", metavar="FILE", help="write cookies to file after operation",
                completer=FileCompleter()),
            arg("--data-binary", metavar="DATA|@FILE", help="POST body sent verbatim (no @file processing)"),
            arg("--data-raw", metavar="DATA", help="POST body verbatim (no @file processing, allow @ literal)"),
            arg("--data-urlencode", metavar="DATA", help="POST data, URL-encoded"),
            arg("--digest", action="store_true", help="use HTTP Digest authentication"),
            arg("--fail", action="store_true", help="fail silently on HTTP errors"),
            arg("--form", metavar="NAME=CONTENT", help="multipart form upload"),
            arg("--head", action="store_true", help="fetch headers only"),
            arg("--header", metavar="HEADER", help="add a request header"),
            arg("--http1.0", action="store_true", help="use HTTP/1.0"),
            arg("--http1.1", action="store_true", help="use HTTP/1.1"),
            arg("--http2", action="store_true", help="use HTTP/2"),
            arg("--http3", action="store_true", help="use HTTP/3"),
            arg("--include", action="store_true", help="include response headers in output"),
            arg("--insecure", action="store_true", help="allow insecure server connections (skip TLS verify)"),
            arg("--ipv4", action="store_true", help="resolve names to IPv4 addresses"),
            arg("--ipv6", action="store_true", help="resolve names to IPv6 addresses"),
            arg("--key", metavar="FILE", help="private key file", completer=FileCompleter()),
            arg("--limit-rate", metavar="SPEED", help="limit transfer speed (e.g. 1K, 1M)"),
            arg("--location", action="store_true", help="follow redirects"),
            arg("--max-redirs", metavar="N", help="maximum number of redirects to follow"),
            arg("--max-time", metavar="SECONDS", help="maximum time allowed for transfer (seconds)"),
            arg("--no-progress-meter", action="store_true", help="do not show progress meter"),
            arg("--noproxy", metavar="HOST-LIST", help="list of hosts that should not use the proxy"),
            arg("--output", metavar="FILE", help="write output to FILE", completer=FileCompleter()),
            arg("--proxy", metavar="[PROTOCOL://]HOST[:PORT]", help="use the given proxy"),
            arg("--proxy-user", metavar="USER[:PASSWORD]", help="proxy user[:password]"),
            arg("--range", metavar="RANGE", help="retrieve only bytes within RANGE"),
            arg("--referer", metavar="URL", help="Referer URL to send"),
            arg("--request", metavar="METHOD", help="specify HTTP method",
                completer=ChoiceCompleter(_HTTP_METHODS)),
            arg("--resolve", metavar="HOST:PORT:ADDR", help="force a host:port to resolve to an address"),
            arg("--retry", metavar="N", help="retry up to N times on transient failures"),
            arg("--retry-delay", metavar="SECONDS", help="wait given seconds between retries"),
            arg("--retry-max-time", metavar="SECONDS", help="give up retrying after given seconds"),
            arg("--silent", action="store_true", help="silent mode"),
            arg("--show-error", action="store_true", help="show errors even when silent"),
            arg("--ssl-no-revoke", action="store_true", help="do not check certificate revocation (Schannel)"),
            arg("--tlsv1.2", action="store_true", help="use TLS 1.2 or later"),
            arg("--tlsv1.3", action="store_true", help="use TLS 1.3 or later"),
            arg("--upload-file", metavar="FILE", help="upload a file (PUT-style)", completer=FileCompleter()),
            arg("--url", metavar="URL", help="URL to work with"),
            arg("--user", metavar="USER[:PASSWORD]", help="user[:password] for server auth"),
            arg("--user-agent", metavar="USER-AGENT", help="User-Agent string to send"),
            arg("--verbose", action="store_true", help="verbose"),
            arg("--write-out", metavar="FORMAT", help="what to display after a transfer"),
        ],
    )
